spring:
  application:
    name: marcia-bot
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: marcia
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

application-configurations:
  discord-bot-token: ODc0NTc4MzEwOTU1NDIxNzE2.GUHBYS.Jk_tF6wTlyE7HsABvcPqg57w4AGC4o_9tnPSso
  telegram-bot-token: 1721139961:AAF2WhC-sOaUbX3ACuj0AfWp2CjnHNwWhi0
  yts-api-base-url: https://yts.mx/api/v2/list_movies.json

