server:
  port: 8082

spring:
  application:
    name: marcia-bot


application-configurations:
  discord-bot-token: ENC(NWHiOARaSmvtxlNFssa+RDbnPwWylV54+NePnwTjfKEzBptiqTS4mwqWpROkBIjZPwAUe/+Jsn4PRyNL7+MAgLdaly5SbBja)
  telegram-bot-token: ENC(CB4hjy6YpiB9qOrVzx6vcQmBug/x3eCLhqwu6fvp2xHIjIsk9tt/6sfVpREdLLX0LJtN6WZGpDI=)
  yts-api-base-url: https://yts.mx/api/v2/list_movies.json

jasypt:
  encryptor:
    password: helloworld