spring:
  application:
    name: marcia-bot


application-configurations:
  discord-bot-token: ODc0NTc4MzEwOTU1NDIxNzE2.GUHBYS.Jk_tF6wTlyE7HsABvcPqg57w4AGC4o_9tnPSso
  telegram-bot-token: 1721139961:AAF2WhC-sOaUbX3ACuj0AfWp2CjnHNwWhi0
  yts-api-base-url: https://yts.mx/api/v2/list_movies.json

