server:
  port: 8082

spring:
  application:
    name: marcia-bot


application-configurations:
  discord-bot-token: ENC(zgKwE10tlCy00vZE3xxClJVWp6/WeWsr623TesZg5CaRfInNkZyKLe33IrjZsKFEqRfWlh8RxGFUBS1/9/KhCJNjnH7okeI5)
  telegram-bot-token: ENC(aXTGyRcaK5Gh+bAOColZZHOv0xo9EJiR0ndUOI7a8x/SU3343yqAdcU0eHPXzPwkCNVzg2RBh/I=)
  yts-api-base-url: https://yts.mx/api/v2/list_movies.json

jasypt:
  encryptor:
    password: ${SECRET_KEY}